name: Maps Scraper

on:
  workflow_dispatch:
    inputs:
      batch_no:
        description: "Batch Number"
        required: true
        default: "1"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          BATCH_NO: ${{ github.event.inputs.batch_no }}
        run: |
          echo "Running Batch $BATCH_NO"
          python scraper.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: business_websites_batch_${{ github.event.inputs.batch_no }}
          path: business_websites.csv
